# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  target 'GiaoHangGiaRe_IOS' do
  
  pod 'FMDB'
  pod 'Alamofire', '~> 4.7.3'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'TPKeyboardAvoiding'
  pod 'NVActivityIndicatorView'
  
end
