# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GiaoHangGiaRe_IOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GiaoHangGiaRe_IOS
    # Swift 3
    # Extended beyond UITextField
    pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
    pod 'Alamofire', '~> 4.7'
end
