// <auto-generated />
namespace GiaoHangGiaRe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateUser10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateUser10));
        
        string IMigrationMetadata.Id
        {
            get { return "201708220110013_updateUser-1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
