// <auto-generated />
namespace GiaoHangGiaRe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_Bang_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_Bang_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201804081117472_update_Bang_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
