// <auto-generated />
namespace GiaoHangGiaRe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class suaTinhTrang_donHang2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(suaTinhTrang_donHang2));
        
        string IMigrationMetadata.Id
        {
            get { return "201803201713358_suaTinhTrang_donHang2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
